// Phase 3: planned shipments and trips.
import { apiAs, BASE, createRunner, ensureSeed, MANAGER, uniq } from './lib.mjs'

export async function run() {
  await ensureSeed()
  const u = uniq()
  const manager = await apiAs(MANAGER)
  await manager.post('/api/users', { email: `driver${u}@test.ua`, password: 'driver123', firstName: 'Водій', lastName: u, role: 'DRIVER', phone: '38063' + u + '9' })
  await manager.post('/api/cars', { plateNumber: 'KA' + u.slice(0, 4) + 'XX', brand: 'Ford', model: 'Transit', active: true })
  const p1 = await manager.post('/api/parcels', { description: 'Для рейсу A ' + u, senderName: 'Відправник A' })
  const p2 = await manager.post('/api/parcels', { description: 'Для рейсу B ' + u, senderName: 'Відправник B' })

  const r = await createRunner('shipments')
  const { page, ok, shot, dialog } = r
  const pickParcel = async (barcode) => {
    await page.fill('[data-slot=dialog-content] input[placeholder*="Штрих-код"]', barcode)
    await page.waitForSelector(`[data-slot=dialog-content] label:has-text("${barcode}")`)
    await page.locator(`[data-slot=dialog-content] label:has-text("${barcode}")`).click()
  }

  try {
    await r.login(MANAGER)
    await page.goto(BASE + '/planned-shipments')
    await page.waitForSelector('h1:has-text("Плановані відправки")')
    await page.getByRole('button', { name: 'Додати' }).click()
    await dialog().waitFor()
    await page.click('[data-slot=dialog-content] button[type=submit]')
    await page.waitForTimeout(300)
    ok('departure required', (await dialog().locator('[data-slot=field-error]').count()) >= 1)
    await page.fill('#ps-departure', '2026-10-05T08:00')
    await page.fill('#ps-arrival', '2026-10-05T07:00')
    await page.click('[data-slot=dialog-content] button[type=submit]')
    await page.waitForTimeout(300)
    ok('arrival before departure rejected', (await dialog().textContent()).includes('Прибуття не може бути раніше'))
    await page.fill('#ps-arrival', '2026-10-05T18:00')
    await page.fill('#ps-origin', 'Київ')
    await page.fill('#ps-destination', 'Львів')
    await page.click('[data-slot=dialog-content] button[type=submit]')
    await page.waitForURL(/\/planned-shipments\/\d+$/)
    await page.waitForSelector('h1:has-text("Відправка #")')
    const plannedUrl = page.url()
    ok('planned shipment created', (await page.textContent('body')).includes('Запланована'), plannedUrl)
    await shot('01-planned-page')
    ok('confirm disabled without car/driver', await page.getByRole('button', { name: 'Підтвердити' }).isDisabled())

    await page.getByRole('button', { name: 'Редагувати' }).click()
    await dialog().waitFor()
    await r.pickSelect('ps-car', 'KA' + u.slice(0, 4))
    await r.pickSelect('ps-driver', u)
    await page.click('[data-slot=dialog-content] button[type=submit]')
    await page.waitForTimeout(600)
    const assigned = await page.textContent('body')
    ok('car and driver assigned', assigned.includes('KA' + u.slice(0, 4)) && assigned.includes('Водій ' + u))
    ok('confirm enabled now', !(await page.getByRole('button', { name: 'Підтвердити' }).isDisabled()))

    await page.getByRole('button', { name: 'Додати посилки' }).click()
    await dialog().waitFor()
    await pickParcel(p1.barcode)
    await pickParcel(p2.barcode)
    ok('two parcels selected', (await dialog().textContent()).includes('Обрано: 2'))
    await shot('02-parcel-picker')
    await dialog().getByRole('button', { name: 'Додати' }).click()
    await page.waitForSelector(`table tbody tr:has-text("${p1.barcode}")`)
    await page.waitForSelector(`table tbody tr:has-text("${p2.barcode}")`)
    ok('parcels added to planned shipment', (await page.textContent('body')).includes('Посилки у відправці (2)'))

    await page.locator(`table tbody tr:has-text("${p2.barcode}")`).getByRole('button', { name: 'Прибрати' }).click()
    await page.waitForSelector('text=Посилки у відправці (1)')
    ok('parcel removed', true)

    await page.getByRole('button', { name: 'Підтвердити' }).click()
    await page.waitForSelector('h1:has-text("Підтверджена")')
    ok('planned shipment confirmed', true)
    await shot('03-planned-confirmed')

    await page.getByRole('button', { name: 'Почати рейс' }).click()
    await dialog().waitFor()
    await page.fill('#st-odo', '120000')
    await dialog().getByRole('button', { name: 'Почати рейс' }).click()
    await page.waitForURL(/\/shipments\/\d+$/)
    await page.waitForSelector('h1:has-text("Рейс #")')
    await page.waitForSelector(`table tbody tr:has-text("${p1.barcode}")`)
    const tripBody = await page.textContent('body')
    ok('trip started with planned parcels', tripBody.includes('У дорозі') && tripBody.includes('Посилки в рейсі (1)'))
    await shot('04-trip')

    await page.goto(plannedUrl)
    await page.waitForSelector('h1:has-text("Виконується")')
    ok('planned shows STARTED and is read-only', (await page.getByRole('button', { name: 'Редагувати' }).count()) === 0)

    await page.goBack()
    await page.waitForSelector('h1:has-text("Рейс #")')
    await page.getByRole('button', { name: 'Завершити' }).click()
    await dialog().waitFor()
    await page.fill('#cp-odo', '100')
    await page.click('[data-slot=dialog-content] button[type=submit]')
    await page.waitForTimeout(300)
    ok('end odometer < start rejected', (await dialog().textContent()).includes('Не може бути менше'))
    await page.fill('#cp-odo', '120350')
    await page.fill('#cp-notes', 'Все доставлено')
    await page.click('[data-slot=dialog-content] button[type=submit]')
    await page.waitForSelector('h1:has-text("Завершений")')
    const done = await page.textContent('body')
    ok('trip completed with odometer & notes', done.includes('120350') && done.includes('Все доставлено'))
    ok('no actions after completion', (await page.getByRole('button', { name: 'Завершити' }).count()) === 0)
    await shot('05-trip-completed')

    await page.goto(BASE + '/shipments')
    await page.waitForSelector('h1:has-text("Рейси")')
    await shot('06-trips-list')
    await page.getByRole('button', { name: 'Почати рейс' }).click()
    await dialog().waitFor()
    await dialog().getByRole('button', { name: 'Почати рейс' }).click()
    await page.waitForTimeout(300)
    ok('ad-hoc trip requires car and driver', (await dialog().locator('[data-slot=field-error]').count()) >= 2)
    await r.pickSelect('st-car', 'KA' + u.slice(0, 4))
    await r.pickSelect('st-driver', u)
    await pickParcel(p2.barcode)
    await dialog().getByRole('button', { name: 'Почати рейс' }).click()
    await page.waitForURL(/\/shipments\/\d+$/)
    await page.waitForSelector(`table tbody tr:has-text("${p2.barcode}")`)
    ok('ad-hoc trip started with picked parcel', (await page.textContent('body')).includes('У дорозі'))
    await page.getByRole('button', { name: 'Скасувати рейс' }).click()
    await dialog().waitFor()
    await dialog().getByRole('button', { name: 'Скасувати рейс' }).click()
    await page.waitForSelector('h1:has-text("Скасований")')
    ok('ad-hoc trip cancelled', true)

    await page.goto(BASE + `/parcels/${p1.id}`)
    await page.waitForSelector('h1:has-text("PT")')
    const pb = await page.textContent('body')
    ok('parcel page links planned & actual shipment', pb.includes('Відправка #') && pb.includes('Рейс #'))

    await page.goto(BASE + '/planned-shipments')
    await page.getByRole('button', { name: 'Додати' }).click()
    await dialog().waitFor()
    await page.fill('#ps-departure', '2026-10-06T08:00')
    await page.click('[data-slot=dialog-content] button[type=submit]')
    await page.waitForURL(/\/planned-shipments\/\d+$/)
    await page.waitForSelector('h1:has-text("Відправка #")')
    await page.getByRole('button', { name: 'Скасувати відправку' }).click()
    await dialog().waitFor()
    await dialog().getByRole('button', { name: 'Скасувати відправку' }).click()
    await page.waitForSelector('h1:has-text("Скасована")')
    ok('planned shipment cancelled', true)
    return r.finish()
  } catch (e) {
    return r.finish(e)
  }
}

if (import.meta.url === `file://${process.argv[1]}`) process.exit((await run()) ? 0 : 1)
